name: tour
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.1
  file_picker: ^8.1.4
  image_picker: ^1.0.5          # ✅ Added for profile photo
  mime: ^1.0.5
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.14.2

  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/company/